Fix Presigned URLs extra slash '/' between Hostaname and the ObjectPath for issue #119
grafana/k6-jslib-aws pull request #120
Opened 2024-12-26 14:35 UTC by Sergei-Kraven

I believe, these changes will fix the issue #119. 

Feel free to leave any comments or suggestions.

2024-12-26 14:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6-jslib-aws?pullRequest=120) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6-jslib-aws?pullRequest=120) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6-jslib-aws?pullRequest=120) it.</sub>

2024-12-26 14:38 UTC, Sergei-Kraven commented
Friendly ping @olegbespalov

2025-01-06 11:07 UTC, oleiade requested changes
Thanks a lot for taking the time to address this @Sergei-Kraven 👏🏻 much appreciated 🙇🏻 

I think the fix makes sense, and seems to work indeed. But would you mind adding a test to ensure it does indeed, and protects us from a regression in the past?

Here's the test I wrote for myself while reviewing this, and put it directly at line 407 in tests/internal/signature.js:```
            describe('should pre-sign requests without doubling encoding the url terminal slash', () => {
                const { query, url } = signer.presign(
                    {
                        method: 'POST',
                        endpoint: new Endpoint('https://foo.us-bar-1.amazonaws.com/'),
                        path: '/foo.txt',
                        headers: {},
                    },
                    presigningOptions
                )

                const expectedURL =                     'https://foo.us-bar-1.amazonaws.com/foo.txt'+
                    '?X-Amz-Algorithm=AWS4-HMAC-SHA256'+
                    '&X-Amz-Credential=foo%2F20000101%2Fus-bar-1%2Ffoo%2Faws4_request'+
                    '&X-Amz-Date=20000101T000000Z'+
                    '&X-Amz-Expires=1800'+
                    '&X-Amz-Signature=c910d7bc4a4f9d5f3db5b0c266d78ddf2c61d0a77628d3adc342e2159ce19895'+
                    '&X-Amz-SignedHeaders=host'

                console.log(`url: ${url}`)
                console.log(`expected url: ${expectedURL}`)
                expect(url).to.equal(expectedURL)
                expect(query).to.deep.equal({
                    [AMZ_ALGORITHM_QUERY_PARAM]: SIGNING_ALGORITHM_IDENTIFIER,
                    [AMZ_CREDENTIAL_QUERY_PARAM]: 'foo/20000101/us-bar-1/foo/aws4_request',
                    [AMZ_DATE_QUERY_PARAM]: '20000101T000000Z',
                    [AMZ_EXPIRES_QUERY_PARAM]: presigningOptions.expiresIn.toString(),
                    [AMZ_SIGNED_HEADERS_QUERY_PARAM]: HOST_HEADER,
                    [AMZ_SIGNATURE_QUERY_PARAM]:
                        'c910d7bc4a4f9d5f3db5b0c266d78ddf2c61d0a77628d3adc342e2159ce19895'
                })
            })
```

Feel free to adapt it 👍🏻

2025-02-13 09:47 UTC, oleiade commented
Hey @Sergei-Kraven 👋🏻 

Do you have capacity to integrate my proposed changes? Otherwise no issue, just let us know and we'll take over 🙇🏻

2025-03-04 13:20 UTC, merged