Add support for SQS
grafana/k6-jslib-aws pull request #27
Opened 2022-12-20 23:58 UTC by nickcaballero

2022-12-20 23:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6-jslib-aws?pullRequest=27) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6-jslib-aws?pullRequest=27) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6-jslib-aws?pullRequest=27) it.</sub>

2023-01-02 13:44 UTC, oleiade requested changes
Hey @nickcaballero 👋🏻 

Thanks a lot for your contribution! This is awesome, really great work 🎉 🦖 💯 

I've left a couple of comments as requested changes. Those are primarily about consistency in naming and documenting the code (we use those comments to write the official documentation later).

Before going forward with this, I would also like to ask you to add a README section dedicated to SQS in the same fashion as with the other services. On top of that, I would kindly ask you to add an example file in the `examples` folder. 

Once those items are addressed, we should be good to go moving forward with merging this 👏🏻 

PS: sorry for the rather late reply, Christmas happened 🎄 🎅🏻 ❄️

2023-01-02 13:44 UTC, oleiade commented on src/internal/sqs.ts
> +    queues: string[]
```suggestion
     /**
      * A list of queue URLs, up to 1,000 entries, or the value of MaxResults you sent in the request.
      */
    queueUrls: string[]
```

2023-01-02 13:44 UTC, oleiade commented on src/internal/sqs.ts
> +    maxResults?: number
```suggestion
    /**
     * Maximum number of results to include in the response. Value range is 1 to 1000. 
     */
    maxResults?: number
```

2023-01-02 13:44 UTC, oleiade commented on src/internal/sqs.ts
> +    nextToken?: string
```suggestion
    /**
     * Pagination token to request the next set of results.
     */
    nextToken?: string
```

2023-01-02 13:44 UTC, oleiade commented on src/internal/sqs.ts
> +    queueNamePrefix?: string
```suggestion
    /**
     * A string to use for filtering the list results. Only those queues whose name begins with the specified string are returned.
     * Queue URLs and names are case-sensitive.
     */
    queueNamePrefix?: string
```

2023-01-02 13:44 UTC, oleiade commented on src/internal/sqs.ts
> +    messageId: string
```suggestion
    /**
     * An attribute containing the MessageId of the message sent to the queue.
     */
    messageId: string
```

2023-01-02 13:44 UTC, oleiade commented on src/internal/sqs.ts
> +    md5OfMessageBody: string
```suggestion
    /**
     * An MD5 digest of the non-URL-encoded message body string. You can use this attribute to verify that Amazon SQS received the message correctly. Amazon SQS URL-decodes the message before creating the MD5 digest. 
     */
    md5OfMessageBody: string
```

2023-01-03 08:51 UTC, oleiade commented on src/internal/signature.ts
> +        request.headers[constants.HOST_HEADER] = request.hostname
This, indeed introduces a bug, and shall be reverted 👍🏻 See #29

2023-01-06 09:32 UTC, oleiade commented
Looks good @nickcaballero 👍🏻 🙇🏻 
Thanks for integrating the requested changes, much appreciated!

Would you say the PR is ready to be merged ❓

2023-01-06 16:11 UTC, nickcaballero commented
> Looks good @nickcaballero 👍🏻 🙇🏻 Thanks for integrating the requested changes, much appreciated!
> 
> Would you say the PR is ready to be merged ❓

Yeah I think so.

2023-01-24 15:48 UTC, oleiade commented
Hi @nickcaballero, great 🤝 

Could you please rebase the current state of the `main` branch? I'll make sure to merge this as soon as it's done. Please let me know when it is and if I can assist you in any ways 😄

2023-01-24 16:17 UTC, nickcaballero commented
@oleiade Done!

2023-01-24 16:21 UTC, oleiade commented
Perfect, thank you very much 🙇🏻 

Merging, and this will go in our next release who doesn't have a set release date at this point, but I'll make sure to notify you here 👏🏻

2023-01-24 16:21 UTC, merged